### ISSUE TITLE
Sensor Read Timing - Coordination with Hivetool

### ISSUE THREAD

**Issue by NapaOgden** [rcrum003/HiveControl#27]
Hivetool and Hive control appear to read sensors at the same time when running concurrently on the same Pi. This had resulted in slow response and Pi hanging maybe due to file locking.
Suggest offset 1 minute before or after or after the on the hour 15 minute interval.

Better yet use one sensor read program and save to two data databases, or even better one database.

**Comment by rcrum003** [comment]
At this point, HiveControl is running all the sensor code from HiveTool, and could be the database. That is a decision by HiveTool at this point. This should be submitted as  request on the HiveTool image page.

**Comment by nanderson77** [comment]
Sorry I guess I’m getting all turned around on these two software packages - Very confusing

So If I’ve got this right.

Pauls HiveTool uses a version of HiveControl, but it’s not what’s posted here on Github?  

Your HiveControl has nothing to do with Paul’s HiveTool?

Paul’s build instructions list installing HiveControl as one of the last steps in his build but he doesn’t use the github to grab stuff.  Is that a separate fork of the code – or is it actually related?

Nate Anderson

Home 763-537-4193

Cell 763-688-0432

Skype 763-634-0115 (nanderson777)

**Comment by rcrum003** [comment]
Sorry for the confusion.
HiveControl is definitely written to support the efforts of HiveTool.

We should really set this up on the image, instead of having users installing.

I'll talk with Paul to get it sorted.

Ryan

**Comment by nanderson77** [comment]
Sorry, not trying to cause confustion… just got turned around.  I saw you’ve been fixing a log of issues, and the HiveTool image isn’t very often updated so I incorrectly hoped I could come right to the source.  

All of my sensors are en-route to my house so I don’t have them hooked up yet but it really seems like your install kit has almost everything scripted to automatically install what Paul manually installs to build his HiveTool image.  Just thinking it may simplify the HiveTool build procedure if the HiveControl software were installed from github first  instead of almost last then the rest of the build procedure should just be adding things that aren’t in HiveControl portion.

If I download the HiveTool image… can I update the HiveControl portion using your update command listed in your readme?  Or will that mess it up?

Nate Anderson

Home 763-537-4193

Cell 763-688-0432

Skype 763-634-0115 (nanderson777)
